skonczono logowanie
dominik762/praktyki24-25 pull request #26
Opened 2024-09-17 07:46 UTC by dominik762

2024-09-17 10:05 UTC, igorleszczynski requested changes

2024-09-17 10:05 UTC, igorleszczynski commented on src/Controllers/AuthUser.php
> +            if (true === self::verifyPassword($password, $email)) {
Zauważ że tutaj dwa razy pobierasz użytkownika. Raz aby go zweryfikować (w środku metody verifyPassword), drugi raz aby przypisać id usera do sesji. Zamiast pobierać z bazy go dwa razy pobierz go nad metodą verifyPassword a następnie przekaż użytkownika poprzez parametr metody.

2024-09-17 10:05 UTC, igorleszczynski commented on src/Controllers/AuthUser.php
> +        var_dump($_SESSION);
Tu jest jakaś pozostałość, jakiś debug. Nie powinno się to tutaj znaleźć - ten var_dump

2024-09-17 10:05 UTC, igorleszczynski commented on src/Controllers/AuthUser.php
> +            if (ini_get("session.use_cookies")) {
ten if moim zdaniem zbędny, wystarczy tylko session_destroy();

2024-09-17 10:05 UTC, igorleszczynski commented on src/Controllers/AuthUser.php
> +            $_SESSION = [];
to też zbędne. session_destroy wystarczy

2024-09-17 10:05 UTC, igorleszczynski commented on src/User.php
> +    public static function findByEmail(mixed $email):?self
Podmień w całym programie te mixed - to jest zła praktyka

2024-09-17 10:05 UTC, igorleszczynski commented on src/Views/UserManagement/AuthUser/register.blade.php
> +if (session_status() === PHP_SESSION_NONE) {
Unikaj implementowania logiki do szablonów. Jest to bardzo zła praktyka. Logika ta często się potem rozwija. Szablon ma służyć tylko do wyświetlania a nie do obsługiwania jakiejś głębszej logiki.

2024-09-17 10:05 UTC, igorleszczynski commented on src/Views/UserManagement/editForm.blade.php
> +if (session_status() === PHP_SESSION_NONE) {
tak samo jak wcześniej, popraw to wszędzie

2024-09-17 10:10 UTC, dominik762 commented on src/Controllers/AuthUser.php
> +        if (session_status() === PHP_SESSION_NONE) {
bez tego nie chciało działać

2024-09-18 09:36 UTC, igorleszczynski requested changes

2024-09-18 09:36 UTC, igorleszczynski commented on src/Redirect.php
> +        $files = array(
Masz wprowadzone na sztywno. Zrób ładowanie plików z pomocą [illuminate/filesystem](https://packagist.org/packages/illuminate/filesystem)

2024-09-18 09:36 UTC, igorleszczynski commented on src/Redirect.php
> +    private static function loadUrls(): array
Obsługi routingu nie powinno być w klasie redirect. Dwie różne rzeczy. Zastanów się nad przeniesieniem tego do klasy Router lub stwórz nową

2024-09-18 11:41 UTC, igorleszczynski requested changes

2024-09-18 11:41 UTC, igorleszczynski commented on src/Urls.php
> +        $files = [
Nie wczytuj plików na sztywno tylko niech zaczyta wszystkie pliki z folderu routes. Pliki tylko z rozszerzeniem .php

2024-09-18 12:07 UTC, igorleszczynski approved these changes

2024-09-18 12:07 UTC, merged