tryby obslugi bledow
dominik762/praktyki24-25 pull request #27
Opened 2024-09-19 10:53 UTC by dominik762

2024-09-20 11:30 UTC, igorleszczynski requested changes

2024-09-20 11:30 UTC, igorleszczynski commented on src/ErrorHandlers/DevErrorHandler.php
> +    public function errorHandler($errno, $errstr, $errfile, $errline): void
brak typów zmiennych

2024-09-20 11:30 UTC, igorleszczynski commented on src/ErrorHandlers/ProdErrorHandler.php
> +    public function errorHandler($errno, $errstr, $errfile, $errline): void
brak typów zmiennych

2024-09-20 11:30 UTC, igorleszczynski commented on src/Interfaces/ErrorHandlerInterface.php
> +    public function errorHandler($errno, $errstr, $errfile, $errline):void;
brak typów zmiennych

2024-09-20 11:30 UTC, igorleszczynski commented on src/Kernel.php
> +            $this->session->start();
sesję lepiej zainicjować na samej górze tej metody. Jeszcze przed headerem. W headerze czasem się może później przydać sesja

2024-09-20 11:30 UTC, igorleszczynski commented on src/Urls.php
> +    public function pickUrl(string $routeKey): string
ta metoda mogła zostać statyczna

2024-09-20 12:04 UTC, dominik762 commented on src/Router.php
> +                foreach ($middlewares as $middleware) {
.

2024-09-20 12:04 UTC, dominik762 commented on src/Router.php
> +                    $middleware->handle();
.

2024-09-23 08:02 UTC, igorleszczynski requested changes

2024-09-23 09:34 UTC, igorleszczynski approved these changes

2024-09-23 09:34 UTC, merged